version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: my-app-task
        LoadBalancerInfo:
          ContainerName: "my-app-container"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
